package com.example.bocchitv.Models.Details

data class AnimeDetails(
    val characters: List<Character>,
    val color: String,
    val countryOfOrigin: String,
    val cover: String,
    val currentEpisode: Int,
    val description: String,
    val duration: Int,
    val endDate: EndDate,
    val episodes: List<Episode>,
    val genres: List<String>,
    val id: String,
    val image: String,
    val isAdult: Boolean,
    val isLicensed: Boolean,
    val malId: Int,
    val nextAiringEpisode: NextAiringEpisode,
    val popularity: Int,
    val rating: Int,
    val recommendations: List<Recommendation>,
    val relations: List<Relation>,
    val releaseDate: Int,
    val season: String,
    val startDate: StartDate,
    val status: String,
    val studios: List<String>,
    val subOrDub: String,
    val synonyms: List<String>,
    val title: TitleXX,
    val totalEpisodes: Int,
    val trailer: Trailer,
    val type: String
)